use Du_An_1;

go
drop TRIGGER CalculateGPA
CREATE TRIGGER CalculateGPA
ON Point
AFTER INSERT
AS
BEGIN
    -- Insert điểm vào bảng Bonus và tính GPA
    INSERT INTO Bonus (Year, Course_Name, Level, ID_Student, GPA, Note)
    SELECT
        i.Year,
        i.Course_Name,
        CASE
            WHEN AVG(i.Point) >= 9.0 THEN 'Excellent'
            WHEN AVG(i.Point) >= 8.0 THEN 'Good'
            WHEN AVG(i.Point) >= 6.5 THEN 'Medium'
            ELSE 'Poor'
        END AS Level,
        i.ID_Student,
        ISNULL(SUM(i.Point) / NULLIF(COUNT(i.Point), 0), 0) AS GPA,
        'Auto-generated by trigger' AS Note
    FROM inserted i
    GROUP BY i.Year, i.Course_Name, i.ID_Student;

    -- Cập nhật điểm trung bình (GPA) trong bảng Bonus
    UPDATE Bonus
    SET GPA = ISNULL((SELECT SUM(Point) / NULLIF(COUNT(Point), 0) FROM Point WHERE ID_Student = Bonus.ID_Student), 0);

END;



